#!/usr/bin/env python3
"""Regenerate the static blog from day-N/*.md source files.

Run this after writing or editing any concepts.md / exercise.md:

    python3 build.py

For each day-N/*.md it writes a sibling day-N/*.html (markdown embedded
inline, no fetch — works opened directly via file://) and regenerates
days.js, which index.html uses to render the day list.
"""
import base64
import json
import re
from datetime import date
from pathlib import Path

WEB_DIR = Path(__file__).parent
TEMPLATE = (WEB_DIR / "_template.html").read_text()


def extract_title(md_text: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def render_page(md_path: Path) -> str:
    md_text = md_path.read_text()
    title = extract_title(md_text, md_path.stem.title())
    b64 = base64.b64encode(md_text.encode("utf-8")).decode("ascii")
    html = TEMPLATE.replace("{{TITLE}}", title).replace("{{MD_B64}}", b64)
    md_path.with_suffix(".html").write_text(html)
    return title


def build_index():
    days = []
    for day_dir in sorted(
        WEB_DIR.glob("day-*"), key=lambda p: int(p.name.split("-")[1])
    ):
        n = int(day_dir.name.split("-")[1])
        concepts_md = day_dir / "concepts.md"
        exercise_md = day_dir / "exercise.md"
        if not concepts_md.exists():
            continue

        entry_date = date.fromtimestamp(concepts_md.stat().st_mtime).isoformat()
        entry = {
            "day": n,
            "date": entry_date,
            "title": render_page(concepts_md),
            "concepts": f"{day_dir.name}/concepts.html",
        }
        if exercise_md.exists():
            entry["exercise"] = {
                "title": render_page(exercise_md),
                "src": f"{day_dir.name}/exercise.html",
            }
        days.append(entry)

    js = "// Generated by build.py — do not edit by hand.\nconst days = "
    js += json.dumps(days, indent=2)
    js += ";\n"
    (WEB_DIR / "days.js").write_text(js)
    return days


if __name__ == "__main__":
    built = build_index()
    names = ", ".join(f"day-{d['day']}" for d in built)
    print(f"Built {len(built)} day(s): {names}")
