// Generated by build.py — do not edit by hand.
const days = [
  {
    "day": 0,
    "date": "2026-08-14",
    "title": "Day 0: How Java Actually Runs",
    "concepts": "day-0/concepts.html",
    "exercise": {
      "title": "Palindrome Check",
      "src": "day-0/exercise.html"
    }
  },
  {
    "day": 1,
    "date": "2026-08-15",
    "title": "Day 1: All Basic Concepts Together",
    "concepts": "day-1/concepts.html",
    "exercise": {
      "title": "Prime Check",
      "src": "day-1/exercise.html"
    }
  },
  {
    "day": 2,
    "date": "2026-08-16",
    "title": "Day 2: Object Oriented Programming",
    "concepts": "day-2/concepts.html",
    "exercise": {
      "title": "GCD & LCM",
      "src": "day-2/exercise.html"
    }
  }
];
