// Generated by build.py — do not edit by hand.
const entries = [
  {
    "number": 0,
    "label": "Entry 0",
    "date": "2026-09-03",
    "title": "Entry 0: Inside the JVM",
    "concepts": "entry-0/concepts.html",
    "exercise": {
      "title": "Palindrome Check",
      "src": "entry-0/exercise.html"
    }
  },
  {
    "number": 1,
    "label": "Entry 1",
    "date": "2026-09-03",
    "title": "Entry 1: All Basic Concepts Together",
    "concepts": "entry-1/concepts.html",
    "exercise": {
      "title": "Prime Check",
      "src": "entry-1/exercise.html"
    }
  },
  {
    "number": 2,
    "label": "Entry 2",
    "date": "2026-09-03",
    "title": "Entry 2: Object Oriented Programming",
    "concepts": "entry-2/concepts.html",
    "exercise": {
      "title": "GCD & LCM",
      "src": "entry-2/exercise.html"
    }
  },
  {
    "number": 2,
    "label": "Entry 2 extra",
    "date": "2026-09-03",
    "title": "Entry 2 extra: Collections, Enums, Exceptions & GC",
    "concepts": "entry-2-extra/concepts.html",
    "exercise": {
      "title": "Factorial & Fibonacci",
      "src": "entry-2-extra/exercise.html"
    }
  },
  {
    "number": 3,
    "label": "Entry 3",
    "date": "2026-09-03",
    "title": "Entry 3: SOLID and shiny day, also some design patterns",
    "concepts": "entry-3/concepts.html",
    "exercise": {
      "title": "Longest Substring Without Repeating Characters",
      "src": "entry-3/exercise.html"
    }
  },
  {
    "number": 4,
    "label": "Entry 4",
    "date": "2026-09-03",
    "title": "Entry 4: O Grande",
    "concepts": "entry-4/concepts.html",
    "exercise": {
      "title": "Reverse a Singly Linked List",
      "src": "entry-4/exercise.html"
    }
  },
  {
    "number": 5,
    "label": "Entry 5",
    "date": "2026-09-03",
    "title": "Entry 5: Data Structures are important",
    "concepts": "entry-5/concepts.html",
    "exercise": {
      "title": "Two Sum",
      "src": "entry-5/exercise.html"
    }
  },
  {
    "number": 6,
    "label": "Entry 6",
    "date": "2026-09-03",
    "title": "Entry 6: Graphs and Trees",
    "concepts": "entry-6/concepts.html",
    "exercise": {
      "title": "Balanced Brackets",
      "src": "entry-6/exercise.html"
    }
  },
  {
    "number": 6,
    "label": "Entry 6 extra",
    "date": "2026-09-03",
    "title": "Entry 6 extra: Crazy extra bits and StringBuilder",
    "concepts": "entry-6-extra/concepts.html",
    "exercise": {
      "title": "Rotate an Array",
      "src": "entry-6-extra/exercise.html"
    }
  },
  {
    "number": 7,
    "label": "Entry 7",
    "date": "2026-09-03",
    "title": "Entry 7: System Design concepts",
    "concepts": "entry-7/concepts.html",
    "exercise": {
      "title": "Permutation Check",
      "src": "entry-7/exercise.html"
    }
  },
  {
    "number": 8,
    "label": "Entry 8",
    "date": "2026-09-03",
    "title": "Entry 8: Load Balancers and Caching",
    "concepts": "entry-8/concepts.html",
    "exercise": {
      "title": "URLify",
      "src": "entry-8/exercise.html"
    }
  },
  {
    "number": 9,
    "label": "Entry 9",
    "date": "2026-09-03",
    "title": "Entry 9: Scaling the Database",
    "concepts": "entry-9/concepts.html",
    "exercise": {
      "title": "Min Stack",
      "src": "entry-9/exercise.html"
    }
  },
  {
    "number": 10,
    "label": "Entry 10",
    "date": "2026-09-03",
    "title": "Entry 10: System Design Concepts Mix",
    "concepts": "entry-10/concepts.html",
    "exercise": {
      "title": "Thread-Safe Counter",
      "src": "entry-10/exercise.html"
    }
  },
  {
    "number": 11,
    "label": "Entry 11",
    "date": "2026-09-03",
    "title": "Entry 11: Spring Roots",
    "concepts": "entry-11/concepts.html",
    "exercise": {
      "title": "LRU Cache",
      "src": "entry-11/exercise.html"
    }
  },
  {
    "number": 12,
    "label": "Entry 12",
    "date": "2026-09-03",
    "title": "Entry 12: Deep Spring",
    "concepts": "entry-12/concepts.html",
    "exercise": {
      "title": "Product Except Self",
      "src": "entry-12/exercise.html"
    }
  },
  {
    "number": 13,
    "label": "Entry 13",
    "date": "2026-09-05",
    "title": "Entry 13: Real Software Products",
    "concepts": "entry-13/concepts.html",
    "exercise": {
      "title": "Best Profit",
      "src": "entry-13/exercise.html"
    }
  },
  {
    "number": 14,
    "label": "Entry 14",
    "date": "2026-09-07",
    "title": "Entry 14: Up & Running in Production",
    "concepts": "entry-14/concepts.html",
    "exercise": {
      "title": "Group Anagrams",
      "src": "entry-14/exercise.html"
    }
  },
  {
    "number": 15,
    "label": "Entry 15",
    "date": "2026-09-08",
    "title": "Entry 15: Relational Databases",
    "concepts": "entry-15/concepts.html",
    "exercise": {
      "title": "Min and Max",
      "src": "entry-15/exercise.html"
    }
  },
  {
    "number": 16,
    "label": "Entry 16",
    "date": "2026-09-10",
    "title": "Entry 16: Networking Basics",
    "concepts": "entry-16/concepts.html",
    "exercise": {
      "title": "Unique Characters",
      "src": "entry-16/exercise.html"
    }
  },
  {
    "number": 17,
    "label": "Entry 17",
    "date": "2026-09-10",
    "title": "Entry 17: Operating Systems and Linux",
    "concepts": "entry-17/concepts.html",
    "exercise": {
      "title": "Palindrome Permutation",
      "src": "entry-17/exercise.html"
    }
  }
];
